theme: jekyll-theme-minimal
title: Kanghyun Lee
description: <p><b>Ph. D. </b><br>Department of ECE, SNU, Seoul, Korea</p>
#logo: https://drive.google.com/uc?id=18gWVNOwDDr0tqDWHURX-45aBHEsQSbj0
# logo: https://drive.google.com/uc?export=view&id=18gWVNOwDDr0tqDWHURX-45aBHEsQSbj0/preview
logo: /assets/img/khlee.jpg
show_downloads: false
google_analytics: 
